name: Publish all tags to Docker Hub

on:
  workflow_dispatch: # Can be manually triggered
  push:
    branches: [ main ]
    paths-ignore:
      - 'docker-compose*.yml'
      - 'README*'
      - 'docs/**'
      - '.github/**'
      - '!.github/workflows/on-push.yml'

jobs:

  build-publish-slim:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - 
        name: Git checkout
        uses: actions/checkout@v3
      - 
        name: Build 'slim'
        id: build-image-slim
        uses: redhat-actions/buildah-build@v2
        with:
          oci: false
          context: .
          containerfiles: Dockerfile.slim
          image: yanwk/barotrauma-server
          tags: slim
      - 
        name: Push to Docker Hub
        id: push-to-dockerhub
        uses: redhat-actions/push-to-registry@v2
        with: 
          image: yanwk/barotrauma-server
          tags: | 
            ${{ steps.build-image-slim.outputs.tags }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      - 
        name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-dockerhub.outputs.registry-paths }}"


  build-publish-preload:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - 
        name: Git checkout
        uses: actions/checkout@v3
      - 
        name: Build 'preload'
        id: build-image-preload
        uses: redhat-actions/buildah-build@v2
        with:
          oci: false
          context: .
          containerfiles: Dockerfile.preload
          image: yanwk/barotrauma-server
          tags: preload
      - 
        name: Push to Docker Hub
        id: push-to-dockerhub
        uses: redhat-actions/push-to-registry@v2
        with: 
          image: yanwk/barotrauma-server
          tags: | 
            ${{ steps.build-image-preload.outputs.tags }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      - 
        name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-dockerhub.outputs.registry-paths }}"


  build-publish-dockerful:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - 
        name: Git checkout
        uses: actions/checkout@v3
      - 
        name: Build 'dockerful'
        id: build-image-dockerful
        uses: redhat-actions/buildah-build@v2
        with:
          oci: false
          context: .
          containerfiles: Dockerfile.dockerful
          image: yanwk/barotrauma-server
          tags: dockerful
      - 
        name: Push to Docker Hub
        id: push-to-dockerhub
        uses: redhat-actions/push-to-registry@v2
        with: 
          image: yanwk/barotrauma-server
          tags: | 
            ${{ steps.build-image-dockerful.outputs.tags }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      - 
        name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-dockerhub.outputs.registry-paths }}"
